CREATE TABLE SRC_CUSTOMERS (
  CUSTOMER_ID NUMBER(10) PRIMARY KEY,
  FULL_NAME   VARCHAR2(200) NOT NULL,
  EMAIL       VARCHAR2(255),
  CREATED_AT  DATE DEFAULT SYSDATE
);

CREATE TABLE SRC_ORDERS (
  ORDER_ID     NUMBER(10) PRIMARY KEY,
  CUSTOMER_ID  NUMBER(10) NOT NULL,
  ORDER_TOTAL  NUMBER(12,2) NOT NULL,
  ORDER_STATUS VARCHAR2(30),
  CREATED_AT   DATE DEFAULT SYSDATE
);
